movie/urls.py
from . import views
from django.urls import path, re_path
from django.urls import include
from django.conf import settings
from django.conf.urls.static import static
from .views import HomePageView, SearchResultsView

app_name = 'movie-review'

urlpatterns = [
    path('', views.home, name='home'),
    path('movie/<int:pk>', views.movie_detail, name='movie_detail'),
    path('genre/<int:pk>', views.genre_detail, name='genre_detail'),
    re_path(r'^home/$', views.home, name='home'),
    path('movie_list', views.movie_list, name='movie_list'),
    path('favorites_id/<int:pk>', views.fav_add, name='favorite'),
    path('favorites_list', views.fav_list, name='favorites_list'),
    path('genre_list', views.genre_list, name='genre_list'),
    path('contact', views.contact, name='contact'),
    path('contact/create/', views.contact_new, name='contact_new'),
    path('review/<int:pk>/create/', views.review_new, name='review_new'),
    path('review/<int:pk>/delete/', views.review_delete, name='review_delete'),
    path('review/<int:pk>/edit/', views.review_edit, name='review_edit'),
    path('profile/<int:pk>/view', views.profile_detail, name="profile_detail"),
    path('profile/<int:pk>/edit', views.profile_edit, name="profile_edit"),
    path('profile/<int:pk>/delete', views.profile_delete, name="profile_delete"),
    path('profile/<int:pk>/private', views.private_add, name='private'),
    path('profile/create/', views.profile_new, name='profile_new'),
    path('search/', SearchResultsView.as_view(), name='search_results'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += [
    path('accounts/', include('django.contrib.auth.urls')),
]

movie/templates/website/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="script" href="{% static "base/script.js" %}">
<script src="{% static "base/script.js" %}"></script>
<link rel="stylesheet" href="{% static "base/styles.css" %}">
<link rel="icon" type="image" href={% static "images/smrlogo.jpeg" %}>

    <head>
        <title>Students' Movie Reviews</title>
    </head>
    <!-- Dark background with white text -->
    <div class="navbar">
        <!--Display navigation options left-justified in navbar -->
        <ul>
            <li>
                <img alt="logo" src={% static "images/smrwhite.png" %}>
            </li>
            <li>
                <a href="{% url 'movie-review:home' %}">Home</a>
            </li>
            <li>
                <a href="{% url 'movie-review:movie_list' %}">Movies</a>
            </li>
            <li>
                <a href="{% url 'movie-review:genre_list' %}">Genres</a>
            </li>
            {% if user.is_authenticated %}
                <li><a href="{% url 'movie-review:favorites_list' %}"><span class="glyphicon glyphicon-log-in"></span>Favorites</a>
                </li>
                {% if user.profile %}
                <li><a href="{% url 'movie-review:profile_detail' pk=user.profile.pk%}"><span class="glyphicon glyphicon-log-in" ></span>View Profile</a>
                </li>
                {% else %}
                <li><a href="{% url 'movie-review:profile_new'%}"><span class="glyphicon glyphicon-log-in" ></span>Create Profile</a>
                </li>
                {% endif %}
                <li><a class="navbarlogin" href="{% url 'logout' %}"><span class="glyphicon glyphicon-log-in" ></span>Logout</a>
                </li>
            {% else %}
                <li><a class="navbarlogin" href="{% url 'login' %}"><span class="glyphicon glyphicon-log-in"></span>Login</a>
                </li>
            {% endif %}
            <li>
                <a href="{% url 'movie-review:contact' %}">Contact Us</a>
            </li>
            <li>
                <div class="SearchBar">
                    <form action="{% url 'movie-review:search_results' %}" method="get">
                    <input name="q" type="text" placeholder="Search Movies" style="padding: 3px; margin-left: 10px">
                    </form>
                </div>
            </li>
        </ul>
    </div>
</div>
<body id="app-layout">
<div class="row">
    <div class="col-md-8">
        {% block content %}
        {% endblock %}
    </div>
</div>
</body>
</html>

movie/templates/website/home.html
<!DOCTYPE html>
<html lang="en">
{% extends 'website/base.html' %}
{% load static %}
{% block content %}
    <body>
    {% if user.is_authenticated %}
        <div class="home">
        <h2 class="top-menu">Hello {{ user.username }},</h2>
        <h1>Welcome to Student Reviews</h1>
        <h2>Check out our featured movies below.</h2>
        <img src="{% static "images/batman.jpg" %}" class="resize" alt="batman">
        <h3>Batman (1989 film)</h3>
        <h3>Summary:</h3>
        <p>After witnessing the death of his beloved parents in front of his face,
            billionaire Bruce Wayne <br> vows himself to protecting the good people of Gotham City against evil forces that threaten the city. <br>
            But his vow is put to the test when he starts to wage his crime fighting crusade against the maniacal <br> Clown Prince of Crime...also known as the Joker.
            </p>
            <iframe width="700" height="500" src="https://www.youtube.com/embed/dgC9Q0uhX70" title="YouTube video player"
                    frameborder="100" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"
                    allowfullscreen></iframe>
            <p><a href="{% url 'movie-review:movie_detail' pk=1 %}">Click here to see reviews for Batman (1989)</a></p>
        <h2>Fan Favorites</h2>
            <p> Click on an image to see reviews</p>
            <div class="clearfix">
                <div class="img-container">
                <a href="{% url 'movie-review:movie_detail' pk=2 %}">
                    <img src="{% static "images/lord of rings.jpg" %}" style="width:75%" alt="lord of the rings">
                </a>
                </div>
                 <div class="img-container">
                <a href="{% url 'movie-review:movie_detail' pk=3 %}">
                    <img src="{% static "images/zulu.jpg" %}" style="width:75%" alt="zulu">
                </a>
                </div>
                <div class="img-container">
                <a href="{% url 'movie-review:movie_detail' pk=4 %}">
                    <img src="{% static "images/monty.jpg" %}" style="width:75%" alt="Monty Python and the Holy Grail">
                </a>
                </div>
                <div class="img-container">
                <a href="{% url 'movie-review:movie_detail' pk=5 %}">
                    <img src="{% static "images/titanic.jpg" %}" style="width:75%" alt="Titanic">
                </a>
                </div>
                <div class="img-container">
                <a href="{% url 'movie-review:movie_detail' pk=6 %}">
                    <img src="{% static "images/starwars.jpg" %}" style="width:75%" alt="Star Wars Episode 4">
                </a>
                </div>
                <div class="img-container">
                <a href="{% url 'movie-review:movie_detail' pk=7 %}">
                    <img src="{% static "images/sixthsense.png" %}" style="width:75%" alt="The Sixth Sense">
                </a>
                </div>

            </div>
    {% else %}
        <div class="home">
        <h1>Welcome to Student Reviews</h1>
        <h2>Check out our featured movies below.</h2>
        <img src="{% static "images/batman.jpg" %}" class="resize" alt="batman">
        <h3>Batman (1989 film)</h3>
        <h3>Summary:</h3>
        <p>After witnessing the death of his beloved parents in front of his face,
            billionaire Bruce Wayne <br> vows himself to protecting the good people of Gotham City against evil forces that threaten the city. <br>
            But his vow is put to the test when he starts to wage his crime fighting crusade against the maniacal <br> Clown Prince of Crime...also known as the Joker.
            </p>
            <iframe width="700" height="500" src="https://www.youtube.com/embed/dgC9Q0uhX70" title="YouTube video player"
                    frameborder="100" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"
                    allowfullscreen></iframe>
            <p><a href="{% url 'movie-review:movie_detail' pk=1 %}">Click here to see reviews for Batman (1989)</a></p>
        <h2>Fan Favorites</h2>
            <p> Click on an image to see reviews</p>
            <div class="clearfix">
                <div class="img-container">
                <a href="{% url 'movie-review:movie_detail' pk=2 %}">
                    <img src="{% static "images/lord of rings.jpg" %}" style="width:75%" alt="lord of the rings">
                </a>
                </div>
                 <div class="img-container">
                <a href="{% url 'movie-review:movie_detail' pk=3 %}">
                    <img src="{% static "images/zulu.jpg" %}" style="width:75%" alt="zulu">
                </a>
                </div>
                <div class="img-container">
                <a href="{% url 'movie-review:movie_detail' pk=4 %}">
                    <img src="{% static "images/monty.jpg" %}" style="width:75%" alt="Monty Python and the Holy Grail">
                </a>
                </div>
                <div class="img-container">
                <a href="{% url 'movie-review:movie_detail' pk=5 %}">
                    <img src="{% static "images/titanic.jpg" %}" style="width:75%" alt="Titanic">
                </a>
                </div>
                <div class="img-container">
                <a href="{% url 'movie-review:movie_detail' pk=6 %}">
                    <img src="{% static "images/starwars.jpg" %}" style="width:75%" alt="Star Wars Episode 4">
                </a>
                </div>
                <div class="img-container">
                <a href="{% url 'movie-review:movie_detail' pk=7 %}">
                    <img src="{% static "images/sixthsense.png" %}" style="width:75%" alt="The Sixth Sense">
                </a>
                </div>

            </div>
        </div>
        </div>
    {% endif %}
    </body>
{% endblock %}
</html>

movie/templates/website/movie_detail.html
{% extends 'website/base.html' %}
{% load mathfilters %}
{% load static %}
{% load index %}
{% block content %}
    <body>
    <div class="profilewrapper">
    <div class="moviedetailwrapper">
  {% if movie %}
  <div class="review">
  <h1>{{ movie.title }}</h1>
  <h4>{{ movie.date }}</h4>
      <p class="reviewp"><strong>Director:</strong> {{ movie.director }}</p>
      <p class="reviewp"><strong>Producer:</strong> {{ movie.producer }}</p>
      <p class="reviewp"><strong>Summary:</strong> {{ movie.summary }}</p>
      <p class="reviewp"><strong>Genres:</strong>
      {% for genre in movie.genre.all %}
          {% if movie.genre.count == 1 %}
              {{ genre.name }}
          {% elif forloop.last %}
              {{ genre.name }}
          {% else %}
              {{ genre.name }},
          {% endif %}
      {% endfor %}
      </p>
      <div style="width: 100%; border-bottom: #FFFFFF 2px solid; padding-top: 20px"></div>
      </div>
      {% if user.is_authenticated %}
          {% if favorite %}
            <div>
                <a href="{% url 'movie-review:favorite' pk=movie.pk %}"><span class="buttondelete">Remove Favorite</span></a>
            </div>
          {% else %}
              <div>
                <a href="{% url 'movie-review:favorite' pk=movie.pk %}"><span class="buttonfavorite">Favorite this Movie</span></a>
            </div>
              {% endif %}
      {% endif %}
      {% else %}
      <p>This movie does not exist.</p>
    {% endif %}
  <h2>Reviews</h2>
    {% if countstars.stars__count >= 1 %}
    <h4>Average Rating: {{ sumstars.stars__sum|div:countstars.stars__count|floatformat:2 }} Stars</h4>
        <div style="padding-bottom: 20px">
     {% with stars=sumstars.stars__sum|div:countstars.stars__count|floatformat:0 %}
        {% if stars == "5" %}
            <h2>⭐️️⭐️️⭐️️⭐️️⭐️️</h2>
        {% elif stars == "4" %}
            <h2>⭐️️⭐️️⭐️️⭐️️</h2>
        {% elif stars == "3" %}
            <h2>⭐️️⭐️️⭐️️</h2>
        {% elif stars == "2" %}
            <h2>⭐️️⭐️️</h2>
        {% elif stars == "1" %}
            <h2>⭐️️️</h2>
         {% endif %}
         </div>
     {% endwith %}
    {% else %}
    <h4>Average Rating: There are no ratings yet.</h4>
    {% endif %}

    {% if user.is_authenticated %}
        <a href="{% url 'movie-review:review_new' pk=movie.pk %}"><span class="buttonadd">Add Review</span></a>
    {% else %}
        <a href={% url 'login' %}><span class="buttonadd">Sign in here to add a review</span></a>
    {% endif %}
    <div style="width: 50%; border-bottom: #FFFFFF 2px solid; padding-top: 20px;"></div>
    <div class="review">
    {% for review in movie.reviews.all %}
        {% if review.user == user %}
                <div class="reviewwrapper">
                    {% if review.user.profile %}
                    <p class="reviewuser"><strong>User: </strong><a href="{% url "movie-review:profile_detail" pk=review.user.profile.pk %}">{{ review.user }}</a></p><div class="reviewprofilepic"><img alt="Profile Picture" src="{{ review.user.profile.image.url }}" style="width: 50px; height: 50px; border-radius: 50%; object-fit: cover; overflow: hidden;"></div></div>
                    {% else %}
                        <p class="reviewp"><strong>User: </strong>{{ review.user }}</p></div>
                    {% endif %}
                <p class="reviewp"><strong>Date: </strong>{{ review.created_date }}</p>
                    {% with stars=review.stars|slugify %}
                            {% if stars == "5" %}
                                <p class="reviewp"><strong>Stars:</strong> ⭐️️⭐️️⭐️️⭐️️⭐️️</p>
                            {% elif stars == "4" %}
                                <p class="reviewp"><strong>Stars:</strong> ⭐️️⭐️️⭐️️⭐️️</p>
                            {% elif stars == "3" %}
                            <p class="reviewp"><strong>Stars:</strong> ⭐️️⭐️️⭐️️</p>
                            {% elif stars == "2" %}
                            <p class="reviewp"><strong>Stars:</strong> ⭐️️⭐️️</p>
                            {% elif stars == "1" %}
                                <p class="reviewp"><strong>Stars:</strong> ⭐️️️</p>
                         {% endif %}
                     {% endwith %}
                <p class="reviewp"><strong>Review Title: </strong>{{ review.title }}</p>
                <p class="reviewp"><strong>Review: </strong>{{ review.content }}</p>
                <a href="{% url 'movie-review:review_edit' pk=review.pk %}"><span class="buttonedit">Edit Review</span></a>
                <a href="{% url 'movie-review:review_delete' pk=review.pk %}"><span class="buttondelete">Delete Review</span></a>
                <div style="width: 100%; border-bottom: #FFFFFF 2px solid; padding-top: 20px"></div>
            {% else %}
            <div class="reviewwrapper">
                {% if review.user.profile %}
                <p class="reviewuser"><strong>User: </strong><a href="{% url "movie-review:profile_detail" pk=review.user.profile.pk%}">{{ review.user }}</a></p><div class="reviewprofilepic"><img alt="Profile Picture" src="{{ review.user.profile.image.url }}" style="width: 50px; height: 50px; border-radius: 50%; object-fit: cover; overflow: hidden;"></div></div>
                {% else %}
                    <p class="reviewp"><strong>User: </strong>{{ review.user }}</p></div>
                {% endif %}
                <p class="reviewp"><strong>Date: </strong>{{ review.created_date }}</p>
                {% with stars=review.stars|slugify %}
                        {% if stars == "5" %}
                            <p class="reviewp"><strong>Stars:</strong> ⭐️️⭐️️⭐️️⭐️️⭐️️</p>
                        {% elif stars == "4" %}
                            <p class="reviewp"><strong>Stars:</strong> ⭐️️⭐️️⭐️️⭐️️</p>
                        {% elif stars == "3" %}
                        <p class="reviewp"><strong>Stars:</strong> ⭐️️⭐️️⭐️️</p>
                        {% elif stars == "2" %}
                        <p class="reviewp"><strong>Stars:</strong> ⭐️️⭐️️</p>
                        {% elif stars == "1" %}
                        <p class="reviewp"><strong>Stars:</strong> ⭐️️️</p>
                     {% endif %}
                 {% endwith %}
            <p class="reviewp"><strong>Review Title: </strong>{{ review.title }}</p>
            <p class="reviewp"><strong>Review: </strong>{{ review.content }}</p>
            <div style="width: 100%; border-bottom: #FFFFFF 2px solid; padding-top: 20px"></div>
        {% endif %}
        <div>
        {% empty %}
            <div>
                <p>No reviews yet.</p>
            </div>
        </div>
        </div>
        </body>
    {% endfor %}
{% endblock %}

movie/templates/website/profile_detail.html
{% extends 'website/base.html' %}
{% load mathfilters %}
{% load static %}
{% load index %}
{% block content %}
    {% if profile.private == False or user.pk == profile.user.pk %}
    <body>
    <div class="profilewrapper">
    <div>
        {% if user.is_authenticated %}
            {% if user.pk == profile.user.pk %}
                <div class="profileactions">
                    <h1 style="border-bottom: 1px solid white; text-align: center;">Actions</h1>
                    {% if profile.private == True %}
                    <div>
                        <a href="{% url 'movie-review:private' pk=profile.pk %}"><span class="buttondelete">Unprivate your profile</span></a><br>
                    </div>
                    {% else %}
                    <div>
                        <a href="{% url 'movie-review:private' pk=profile.pk %}"><span class="buttonadd">Private your profile</span></a><br>
                    </div>
                    {% endif %}
                    <a href="{% url 'movie-review:profile_edit' pk=profile.pk %}"><span class="buttonedit">Edit Profile</span></a><br>
                    <a href="{% url 'movie-review:profile_delete' pk=profile.pk %}"><span class="buttondelete">Delete Profile</span></a><br>
                </div>
                {% endif %}
        {% endif %}
    <div class="casbah">
        <div class="profileimage">
        <div><img alt="Profile Picture" src="{{ profile.image.url }}" style="width: 200px; height: 200px; border-radius: 50%; object-fit: cover">
            <div><h1>{{ profile.user.username }}</h1></div></div></div>
        <h2>Biography</h2>
        <div><p>{{ profile.bio }}</p></div>
        <h2>Social Media</h2>
        {% if profile.websiteurl %}
        <div><a href="{{ profile.websiteurl }}">Website</a></div>
        {% endif %}
        {% if profile.facebookurl %}
        <div><a href="{{ profile.facebookurl }}">Facebook</a></div>
        {% endif %}
        {% if profile.instagramurl %}
        <div><a href="{{ profile.instagramurl }}">Instagram</a></div>
        {% endif %}
        {% if profile.twitterurl %}
        <div><a href="{{ profile.twitterurl }}">Twitter</a></div>
        {% endif %}
        </div>
        </div>
        <div class="casbah">
        {% if user.is_authenticated %}
            {% if user.pk == profile.user.pk %}
                {% if profile.user.reviews.all %}
                <h1>Reviews:</h1>
                {% for review in profile.user.reviews.all %}
                    <div class="profilereviews">
                    <p class="reviewp"><strong>Review Title: </strong>{{ review.title }}</p>
                    <p class="reviewp"><strong>Review: </strong>{{ review.content }}</p>
                        {% with stars=review.stars|slugify %}
                            {% if stars == "5" %}
                            <p>Stars: ⭐️️⭐️️⭐️️⭐️️⭐️️</p>
                            {% elif stars == "4" %}
                            <p>Stars: ⭐️️⭐️️⭐️️⭐️️</p>
                            {% elif stars == "3" %}
                            <p>Stars: ⭐️️⭐️️⭐️️</p>
                            {% elif stars == "2" %}
                            <p>Stars: ⭐️️⭐️️</p>
                            {% elif stars == "1" %}
                            <p>Stars: ⭐️️️</p>
                         {% endif %}
                     {% endwith %}
                    <a href="{% url 'movie-review:review_edit' pk=review.pk %}"><span class="buttonedit">Edit Review</span></a>
                    <a href="{% url 'movie-review:review_delete' pk=review.pk %}"><span class="buttondelete">Delete Review</span></a>
                    </div>
                {% endfor %}
                    {% endif %}
                {% endif %}
        {% endif %}
        </div>
    </div>
    </body>
        {% else %}
        <h1>This profile is locked or does not exist.</h1>
    {% endif %}
{% endblock %}

movie/templates/website/profile_edit.html
{% extends 'website/base.html' %}
{% load crispy_forms_filters %}
{% load crispy_forms_tags %}
<!DOCTYPE html>
<html lang="en">
{% block content %}
    <body>
    <div class="formwrapper" style="background-color: rgba(217, 179, 130, .05)">
    <h1>Edit Your Profile</h1>
    <div class="formcontent">
    <form method="POST" class="review-form" enctype="multipart/form-data">{% csrf_token %}
         {{ form|crispy }}
        <div class="formcontent">
        <button type="submit" class="buttonadd">Save</button>
        </div>
    </form>
    </div>
    </div>
    </body>
{% endblock %}
</html>

movie/templates/website/profile_new.html
{% extends 'website/base.html' %}
{% load crispy_forms_filters %}
{% load crispy_forms_tags %}
<!DOCTYPE html>
<html lang="en">
{% block content %}
    <body>
    <div class="formwrapper">
    <h1>Create Your Profile</h1>
    <div class="formcontent">
    <form method="POST" class="review-form" enctype="multipart/form-data">{% csrf_token %}
         {{ form|crispy }}
        <div class="formcontent">
        <button type="submit" class="buttonadd">Save</button>
        </div>
    </form>
    </div>
    </div>
    </body>
{% endblock %}
</html>

movie/templates/website/review_confirm.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <p> You have added a review to Students' Movie Reviews</p>
</head>
<body>

</body>
</html>

movie/templates/website/review_delete_email.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <p> You have deleted your review on Students' Movie Reviews</p>
</head>
<body>

</body>
</html>

movie/templates/website/review_edit_email.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <p> You have edited your review on Students' Movie Reviews</p>
</head>
<body>

</body>
</html>

movie/templates/website/review_new.html
{% extends 'website/base.html' %}
{% load crispy_forms_filters %}
{% load crispy_forms_tags %}
<!DOCTYPE html>
<html lang="en">
{% block content %}
    <body>
    <div class="formwrapper">
    <h1>Add a New Review</h1>
    <div class="formcontent">
    <form method="POST" class="profile-form">{% csrf_token %}
         {{ form|crispy }}
        <div class="formcontent">
            {% if user.pk in movie.reviews.users %}
        <button type="submit" class="buttonadd" onclick="alert('You have already submitted a review for this movie.')">Save</button>
            {% else %}
        <button type="submit" class="buttonadd">Save</button>
            {% endif %}
        </div>
    </form>
    </div>
    </div>
    </body>
{% endblock %}
</html>

movie/templates/website/search_results.html
<!DOCTYPE html>
<html lang="en">
{% extends 'website/base.html' %}
{% load static %}
{% block content %}
    <body>
    <div class="list-container">
     <div class="list-wrapper">
        <div class="panel panel-primary">
            <div class="panel-heading">Welcome!
            <div class="panel-body">
                Students' Movie Review - Make your opinion known.
            </div>
        </div>
    </div>
    <h1>Search Results</h1>
            <table class="styled-table">
            <thead>
            <tr>
                <th>Movie Name</th>
                <th>Movie Director</th>
                <th>Movie Producer</th>
                <th>Movie Date</th>
                <th>Amount of Reviews</th>
            </tr>
            </thead>
            <tbody>
  {% for movie in object_list %}
      <tr>
        <td><a href="{% url 'movie-review:movie_detail' pk=movie.pk %}">{{ movie.title }}</a>
        <td>{{ movie.director }}</td>
        <td>{{ movie.producer }}</td>
        <td>{{ movie.date }}</td>
        <td>{{ movie.reviews.count }}</td>
  {% empty %}
      <h2> No Movies were found</h2>
  {% endfor %}

        </tr>

            </tbody>
        </table>
    </div>
     </div>
    </div>
    </body>
{% endblock %}
</html>